### ISSUE TITLE
Item box pages not working

### ISSUE THREAD

**Issue by XioNUndead** [Chakratos/mhf-save-manager#13]
Hey, unless I'm doing this completely wrong, but I got a max item box page of 40 and I'm trying to give myself more like 63 pages for example it says that the value 4000 = 40 pages so would 6300 = 63 pages? if so, I'm doing this but it's not changing in the editor at all.

Any idea why? sorry to put this in the Issue box I didn't know any other way to get in touch

Edit: Never mind i figured it out sorry about the inconvenient

**Comment by Chakratos** [comment]
Greetings @XioNUndead,
As you probably saw, the config is only for the item box editor view.
Increasing itembox pages isn't that easy, as it is tied to the House upgrades, distribution gifts and other things
