### ISSUE TITLE
Backup saves importing is not working correctly

### ISSUE THREAD

**Issue by Dedsonic** [Chakratos/mhf-save-manager#14]
When i try to import my old save into a pre existing save nothing happens, and i've yet to figure out why that is. I can create backups of my save, but if i download that backup, and import it back into the save manager it won't register either. Meaning that for some reason the save manager can only create backups but not import them. I am at a complete loss here, any help would be appreciated!

**Comment by Chakratos** [comment]
Greetings, it seems like some sort of permission problem to me, have you tried running it as admin?

You could also try to go inside the www folder -> storage -> savedata -> Character ID -> and pasting the downloaded .bin here. 
This is the folder where the save manager stores all its saves for that character
