### ISSUE TITLE
Request to add support for missing files.

### ISSUE THREAD

**Issue by Sera9145** [Chakratos/mhf-save-manager#15]
There is 3 extra files that store data for a player which are not in the save manager as of now.
Those files are Minidata, Scenariodata and Savefavouritequest.
Would be cool to get those saved easily through the manager aswell, especially since scenariodata holds everything for the series quests.

**Comment by Chakratos** [comment]
Thanks for reporting, will add them asap

**Comment by Chakratos** [comment]
Sorry for the long wait, the code is written and will be released today :)
