### ISSUE TITLE
Error 500 : Internal Server Error

### ISSUE THREAD

**Issue by JLHat** [Chakratos/mhf-save-manager#16]
![problem](https://user-images.githubusercontent.com/110543963/216315722-3ce1b3ff-79bc-4040-9962-c90f4188f310.JPG)
Sorry for bothering. I got this error after I update my erupe server to 9.1. I'm using version 1.6.1. the older version didn't work either.
It would be grateful if someone could solve the problem.

Edit: I figured out the problem. It seems like something is wrong with my visual c++, after reinstalling, the problem is solved.

**Comment by Chakratos** [comment]
Great that you could solve the problem :)
