### ISSUE TITLE
Update Roadshop Editor

### ISSUE THREAD

**Issue by Malckyor** [Chakratos/mhf-save-manager#17]
As of this [commit](https://github.com/ZeruLight/Erupe/commit/9103debe995d5abaabd930460bd947d1921e9242#diff-c8c484a1e3f96239a99fcdc27be93b4027a2cc7aa894cd12ef8a0ab2c7b335ce) the normal_shop_items collumns were renamed making the current version no more compatible with it, an update is required for this feature.

**Comment by Chakratos** [comment]
Greetings @Malckyor,
thanks for reporting!
Fixes going live today :)
