### ISSUE TITLE
Error at starting up

### ISSUE THREAD

**Issue by Soakinho** [Chakratos/mhf-save-manager#18]
I have this error while trying to run "phpdesktop-chrome":
![image](https://user-images.githubusercontent.com/125149154/218273099-e5119fe9-1128-41fe-aa41-d02a5590d0d7.png)
What could be the problem?
My config file is like this:
![image](https://user-images.githubusercontent.com/125149154/218273230-db442551-1834-4e48-9c1d-d6d8dd8433f1.png)

**Comment by Chakratos** [comment]
Hello, it seems that the postgres Database is not running on your machine, or maybe inside a Docker which refuses Connections from outside.
Could you tell me where your Database is installed / running?

**Comment by Soakinho** [comment]
Hello, I do not know which Database are you pointing out. I am running as you told us in the Read me.
My file is in local and look like this.
![image](https://user-images.githubusercontent.com/125149154/218872232-9fca36ac-6d0c-4ec0-816d-6570346a1bf2.png)
I can tell you more info if you guide me through it.

**Comment by Chakratos** [comment]
You are running your own MHF Server (Erupe) right?

If you are playing on an public server hosted by others you cannot use this tool.

By PostgreSQL Database i mean the database settings also needed inside the erupe config

**Comment by Soakinho** [comment]
I see, yes I am playing in Frontier International Server, so it might not be working because of this.
Really appreciate, thank you for your time!
