### ISSUE TITLE
Inventory Space

### ISSUE THREAD

**Issue by XioNUndead** [Chakratos/mhf-save-manager#20]
Good Day, on the manager we can only go up to 40 pages for the itembox but in game i got 63 pages is there a way to add more box space on the manager as well? thank you in advance :)

**Comment by Chakratos** [comment]
Greetings, in the config.php you can increase the itembox pages shown. But beware, increasing it too high shows some random items, DONT edit them or add new ones after seeing them in the pages as that is random data of your savedata.
The Itembox seems to be splitted and i have not found the other halve yet so before editing make backups!
