### ISSUE TITLE
Save Manager not working

### ISSUE THREAD

**Issue by Dixdros** [Chakratos/mhf-save-manager#21]
Seems like because of the Gacha DB the Save Manager is not more compatible anymore and nothing works anymore https://github.com/ZeruLight/Erupe/blob/main/patch-schema/gacha-db.sql  https://github.com/ZeruLight/Erupe/blob/main/patch-schema/gacha-db-2.sql

**Comment by Chakratos** [comment]
Hey, it took me some days to make it compatible again but the newest release should be 100% compatible again :)
