### ISSUE TITLE
roadshop error

### ISSUE THREAD

**Issue by Elzric** [Chakratos/mhf-save-manager#22]
![image](https://user-images.githubusercontent.com/129649459/229338137-06ba8436-c57e-4ea3-a9f8-a028c0e66869.png)
I don't know if it's because I have the main version of erupe but I get this

**Comment by Chakratos** [comment]
Greetings, the current release should be only compatible with the newest Erupe version. It took me some days to make a new release compatible again. Please try out the newest one :)
