### ISSUE TITLE
About errors at startup

### ISSUE THREAD

**Issue by csgiisy** [Chakratos/mhf-save-manager#5]
素晴らしいツールの作成をありがとうございます。
起動時に以下のエラーが発生してしまうので修正方法があればご教授頂けないでしょうか。

「Fatal error: Uncaught PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR: 列t0.gcpは存在しません LINE 1: ...t0.name AS name_5, t0.last_login AS last_login_6, t0.gcp AS ... ^ in C:\MHF_TOOL\MHFSaveManager\www\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:78 Stack trace: #0 C:\MHF_TOOL\MHFSaveManager\www\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(78): PDO->query('SELECT t0.id AS...') #1 C:\MHF_TOOL\MHFSaveManager\www\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(911): Doctrine\DBAL\Driver\PDOConnection->query('SELECT t0.id AS...') #2 C:\MHF_TOOL\MHFSaveManager\www\vendor\doctrine\orm\lib\Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php(889): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array) #3 C:\MHF_TOOL\MHFSaveManager\www\vendor\doctrine\orm\lib\Doctrine\ORM\EntityRepository.php(178): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL) in C:\MHF_TOOL\MHFSaveManager\www\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDriver.php on line 60」

**Comment by Chakratos** [comment]
親切な言葉をありがとう、他のモンスターハンターファンのためにこのアプリケーションを作成できて光栄です！
どのバージョンのErupeを使用しているか教えてください。
エラーは、データベーステーブル "characters" から欠落している列があることを意味します

**Comment by csgiisy** [comment]
Thank you for your reply.
The version we are using is "1.5.3".
We have also confirmed that the error does not occur until version "1.3.0", but this issue occurs after version "1.4.1".

**Comment by Chakratos** [comment]
The version of the save-manager is correct, the error is caused by Erupe (The serverfiles of MHF)
Are you sure you installed the MHF server correct?
Where did you download Erupe from?

The save-manager is only compatible with the community edition:
https://drive.google.com/drive/folders/1F_xg7qaFmG_L7AJ16vzYBG8pwlpCYSFN

If there is another version you use, please tell me so i can look into supporting it too :)

**Comment by csgiisy** [comment]
Thank you for your reply.
We used the server program you gave us and recreated the DB, and confirmed that it starts with version "1.5.3".
Thank you very much for your kind attention.
We look forward to waiting for further evolution of the program.
