### ISSUE TITLE
Trying to upload backup refreshes the page and does nothing. 

### ISSUE THREAD

**Issue by EclipseKnight** [Chakratos/mhf-save-manager#6]
When attempting to upload a backup.bin, the screen flashes as if refreshing and doesn't actually upload. This is as of version 1.5.3.

I'm connecting to a remote postgres server running postgres 12 on ubuntu.

**Comment by Chakratos** [comment]
Greetings,
if you are using the Noob Method then please try running phpdesktop as Admin, it seems to be a permission issue.
Sadly i cannot force admin permissions.

If you are running your own webserver, check if the file permissions are set correct for the Apache / NGinx instance
